language: python
python:
  - 2.6
  - 2.7
  - 3.3
env:
  - DJANGO=Django==1.4.8
  - DJANGO=Django==1.5.4
  - DJANGO=https://www.djangoproject.com/download/1.6b4/tarball/
install:
  - pip install $DJANGO
  - pip install -r example_project/requirements_test.txt
  - python setup.py install
script:
  - cd example_project
  - python manage.py test django_mptt_example
  - coverage run --source=django_mptt_admin,django_mptt_example manage.py test django_mptt_example
  - coverage report -m
after_success:
  - pip install -r requirements_coveralls.txt
  - coveralls
matrix:
  exclude:
    - python: 3.3
      env: DJANGO==1.4.8
branches:
  only:
    - master