language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.3.5
  - DJANGO_VERSION=1.4.3
install:
  - pip install django-mptt==0.5.5 six==1.2.0 Django==$DJANGO_VERSION
  - pip install -r example_project/requirements_test.txt
  - python setup.py -q install
script:
  - cd example_project
  - mkdir -p reports
  - python manage.py jenkins