language: python
python:
  - 2.6
  - 2.7
  - 3.3
env:
  - DJANGO=Django==1.4.9
  - DJANGO=Django==1.5.5
  - DJANGO=https://www.djangoproject.com/download/1.6b4/tarball/
install:
  - pip install $DJANGO
  - pip install -r example_project/requirements_test.txt
  - python setup.py install
script:
  - cd example_project
  - python manage.py test django_mptt_example
  - coverage run --source=django_mptt_admin,django_mptt_example manage.py test django_mptt_example
  - coverage report -m
before_install:
  - pip install pep8 pip-tools
  - sudo apt-get update -qq
  - sudo apt-get install -qq sloccount
after_success:
  - pip install -r requirements_coveralls.txt
  - coveralls
  - pip install coviolations_app==0.18
  - cd ..
  - covio
matrix:
  exclude:
    - python: 3.3
      env: DJANGO=Django==1.4.9
branches:
  only:
    - master