language: python
python:
  - 2.6
  - 2.7
  - 3.3
env:
  - DJANGO_VERSION=1.3.7
  - DJANGO_VERSION=1.4.5
  - DJANGO_VERSION=1.5
install:
  - pip install Django==$DJANGO_VERSION
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install git+git://github.com/tow/django-mptt.git@70a02b808735581d4a848acac7429e0525082330; else pip install django-mptt==0.5.5; fi"
  - pip install six==1.2.0
  - pip install -r example_project/requirements_test.txt
  - python setup.py install
script:
  - cd example_project
  - mkdir -p reports
  - python manage.py jenkins
matrix:
  exclude:
    - python: 3.3
      env: DJANGO_VERSION=1.3.7
    - python: 3.3
      env: DJANGO_VERSION=1.4.5