language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.3.5
  - DJANGO_VERSION=1.4.3
  - DJANGO_VERSION=1.5c1
install:
  - "if [[ $DJANGO_VERSION == '1.5c1' ]]; then pip install https://www.djangoproject.com/download/1.5c1/tarball/; else pip install Django==$DJANGO_VERSION; fi"
  - pip install django-mptt==0.5.5 six==1.2.0
  - pip install -r example_project/requirements_test.txt
  - python setup.py install
script:
  - cd example_project
  - mkdir -p reports
  - python manage.py jenkins