language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - pypy
env:
  - DJANGO=Django==1.7.7
  - DJANGO=Django==1.8
install:
  - pip install $DJANGO
  - pip install -r example_project/requirements.txt
  - pip install -r example_project/requirements_test.txt
  - pip install -r example_project/requirements_travis.txt
  - pip install -e .
script:
  - python example_project/manage.py test django_mptt_example
  - coverage run --source=django_mptt_admin,example_project/django_mptt_example example_project/manage.py test django_mptt_example
  - coverage report
after_success:
  - coveralls
matrix:
  exclude:
    - python: 2.6
      env: DJANGO=Django==1.7.7
    - python: 2.6
      env: DJANGO=Django==1.8
    - python: pypy
      env: DJANGO=Django==1.8
branches:
  only:
    - master
