language: python
sudo: false
python:
  - 2.7
  - 3.4
  - 3.5
env:
  - DJANGO="Django==1.8.14 django-mptt==0.8.5"
  - DJANGO="Django==1.9.9 django-mptt==0.8.5"
  - DJANGO="Django==1.10 https://github.com/matthiask/django-mptt/archive/mk/nomagic.zip"
  - DJANGO="https://github.com/django/django/archive/master.tar.gz https://github.com/matthiask/django-mptt/archive/mk/nomagic.zip"
install:
  - pip install $DJANGO
  - pip install -r example_project/requirements.txt
  - pip install -r example_project/requirements_test.txt
  - pip install -r example_project/requirements_travis.txt
  - pip install -e .
script:
  - python example_project/manage.py test django_mptt_example
  - coverage run --source=django_mptt_admin,example_project/django_mptt_example example_project/manage.py test django_mptt_example
  - coverage report
after_success:
  - coveralls
