language: python
sudo: false
python:
  - 2.7
  - 3.4
  - 3.5
  - pypy
env:
  - DJANGO=Django==1.7.10
  - DJANGO=Django==1.8.6
  - DJANGO=https://www.djangoproject.com/download/1.9b1/tarball/
install:
  - pip install $DJANGO
  - pip install -r example_project/requirements.txt
  - pip install -r example_project/requirements_test.txt
  - pip install -r example_project/requirements_travis.txt
  - pip install -e .
script:
  - python example_project/manage.py test django_mptt_example
  - coverage run --source=django_mptt_admin,example_project/django_mptt_example example_project/manage.py test django_mptt_example
  - coverage report
after_success:
  - coveralls
matrix:
  exclude:
    - python: pypy
      env: DJANGO=Django==1.8.6
    - python: pypy
      env: DJANGO=https://www.djangoproject.com/download/1.9b1/tarball/
    - python: 3.5
      env: DJANGO=Django==1.7.10
branches:
  only:
    - master
