language: python
sudo: false
python:
  - 2.7
  - 3.5
  - 3.6
env:
  - DJANGO="Django==1.8.17"
  - DJANGO="Django==1.9.12"
  - DJANGO="Django==1.10.6"
  - DJANGO="https://www.djangoproject.com/download/1.11b1/tarball/"
  - DJANGO="https://github.com/django/django/archive/master.zip"
install:
  - pip install $DJANGO
  - pip install -r example_project/requirements.txt
  - pip install -r example_project/requirements_test.txt
  - pip install -r example_project/requirements_travis.txt
  - pip install -e .
script:
  - python example_project/manage.py test django_mptt_example
  - coverage run --source=django_mptt_admin,example_project/django_mptt_example example_project/manage.py test django_mptt_example
  - coverage report
after_success:
  - coveralls
matrix:
  exclude:
  - python: 2.7
    env: DJANGO="https://github.com/django/django/archive/master.zip"
