language: python
python:
  - 2.6
  - 2.7
  - 3.3
env:
  - DJANGO=Django==1.4.13
  - DJANGO=Django==1.5.8
  - DJANGO=Django==1.6.5
  - DJANGO=https://www.djangoproject.com/m/releases/1.7/Django-1.7b4.tar.gz
install:
  - pip install $DJANGO
  - pip install -r example_project/requirements.txt
  - pip install -r example_project/requirements_test.txt
  - pip install -r example_project/requirements_travis.txt
  - python setup.py install
script:
  - cd example_project
  - python manage.py test django_mptt_example
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq sloccount
after_success:
  - coveralls
  - cd ..
  - covio
matrix:
  exclude:
    - python: 2.6
      env: DJANGO=https://www.djangoproject.com/m/releases/1.7/Django-1.7b4.tar.gz
    - python: 3.3
      env: DJANGO=Django==1.4.13
branches:
  only:
    - master
