language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - pypy
env:
  - DJANGO=Django==1.4.19
  - DJANGO=Django==1.5.12
  - DJANGO=Django==1.6.10
  - DJANGO=Django==1.7.5
  - DJANGO=https://www.djangoproject.com/download/1.8b1/tarball/
install:
  - pip install $DJANGO
  - pip install -r example_project/requirements.txt
  - pip install -r example_project/requirements_test.txt
  - pip install -r example_project/requirements_travis.txt
  - pip install -e .
script:
  - python example_project/manage.py test django_mptt_example
  - coverage run --source=django_mptt_admin,example_project/django_mptt_example example_project/manage.py test django_mptt_example
  - coverage report
after_success:
  - coveralls
matrix:
  exclude:
    - python: 2.6
      env: DJANGO=Django==1.7.5
    - python: 2.6
      env: DJANGO=https://www.djangoproject.com/download/1.8b1/tarball/
    - python: 3.3
      env: DJANGO=Django==1.4.19
    - python: 3.4
      env: DJANGO=Django==1.4.19
    - python: pypy
      env: DJANGO=Django==1.4.19
    - python: pypy
      env: DJANGO=Django==1.5.12
    - python: pypy
      env: DJANGO=Django==1.6.10
branches:
  only:
    - master
