language: python
sudo: false
python:
  - 2.7
  - 3.4
  - 3.5
env:
  - DJANGO=Django==1.7.11 django-mptt==0.7.4
  - DJANGO=Django==1.8.11 django-mptt==0.8.3
  - DJANGO=Django==1.9.4 django-mptt==0.8.3
install:
  - pip install $DJANGO
  - pip install -r example_project/requirements.txt
  - pip install -r example_project/requirements_test.txt
  - pip install -r example_project/requirements_travis.txt
  - pip install -e .
script:
  - python example_project/manage.py test django_mptt_example
  - coverage run --source=django_mptt_admin,example_project/django_mptt_example example_project/manage.py test django_mptt_example
  - coverage report
after_success:
  - coveralls
matrix:
  exclude:
    - python: 3.5
      env: DJANGO=Django==1.7.11
branches:
  only:
    - master
