language: python
python:
  - 2.6
install:
  - pip install -r example_project/requirements.txt
  - pip install -r example_project/requirements_test.txt
script:
  - cd example_project
  - mkdir -p reports
  - python manage.py jenkins